**Aim: To implement Logistic Regression for binary classification problem and analyze the classification performance.**

In [ ]:
import seaborn as sns
import pandas as pd
import numpy as np

In [ ]:
df = sns.load_dataset('iris')
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [ ]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [ ]:
df.shape

(150, 5)

In [ ]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [ ]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [ ]:
# Remove the setosa category from dataset for binary classification
df=df[df['species']!='setosa'].copy()

In [ ]:
df.shape

(100, 5)

In [ ]:
df['species'].unique()

array([0, 1])

In [ ]:
df['species'] = df['species'].map({'versicolor': 0, 'virginica': 1})

In [ ]:
df.head()

    sepal_length  sepal_width  petal_length  petal_width  species
50           7.0          3.2           4.7          1.4      NaN
51           6.4          3.2           4.5          1.5      NaN
52           6.9          3.1           4.9          1.5      NaN
53           5.5          2.3           4.0          1.3      NaN
54           6.5          2.8           4.6          1.5      NaN

In [ ]:
# Split dataset into independant and depedent features
X = df.iloc[:,:-1]
print(X)

     sepal_length  sepal_width  petal_length  petal_width
50            7.0          3.2           4.7          1.4
51            6.4          3.2           4.5          1.5
52            6.9          3.1           4.9          1.5
53            5.5          2.3           4.0          1.3
54            6.5          2.8           4.6          1.5
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[100 rows x 4 columns]

In [ ]:
y = df.iloc[:,-1]
print(y)

50    NaN
51    NaN
52    NaN
53    NaN
54    NaN
       ..
145   NaN
146   NaN
147   NaN
148   NaN
149   NaN
Name: species, Length: 100, dtype: float64

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7,test_size=0.3,random_state=42)

In [ ]:
print(X_train.shape)

(70, 4)

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier= LogisticRegression()

In [ ]:
from inspect import Parameter
from sklearn.model_selection import GridSearchCV
parameter={'penalty':['l1','l2','elasticnet'], 'C':[1,2,3,4,5,6,10,20,30,40,50],
           'max_iter':[100,200,300,400]}

In [ ]:
classifier_regressor = GridSearchCV(
    classifier,
    param_grid=parameter,
    scoring='accuracy',
    cv=5
)

In [ ]:
classifier_regressor.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/_array_api.py:399: RuntimeWarning: invalid value encountered in cast
  return x.astype(dtype, copy=copy, casting=casting)

ValueError: Input y contains NaN.